=== jpbruckler/PowerIAM/src/PowerIAM/App/navigation.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Menu Schema",
    "description": "Schema for menu configuration with nodes and child nodes.",
    "type": "object",
    "properties": {
        "home": {
            "$ref": "#/definitions/node"
        },
        "search": {
            "$ref": "#/definitions/node"
        },
        "userManagement": {
            "$ref": "#/definitions/node"
        },
        "groupManagement": {
            "$ref": "#/definitions/node"
        },
        "operations": {
            "$ref": "#/definitions/node"
        },
        "settings": {
            "$ref": "#/definitions/node"
        }
    },
    "additionalProperties": false,
    "definitions": {
        "node": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "href": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "roles": {
                    "$ref": "#/definitions/roles"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/childNode"
                    }
                }
            },
            "required": [
                "label"
            ],
            "additionalProperties": false
        },
        "childNode": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "href": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "roles": {
                    "$ref": "#/definitions/roles"
                }
            },
            "required": [
                "label"
            ],
            "additionalProperties": false
        },
        "roles": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "PowerIAM Administrators",
                    "PowerIAM Operators",
                    "PowerIAM Users",
                    "Administrator"
                ]
            },
            "uniqueItems": true
        }
    }
}

=== jpbruckler/PowerIAM/src/PowerIAM/App/navigation.json
{
    "home": {
        "label": "Home",
        "icon": "home",
        "href": "/",
        "path": "Home.ps1"
    },
    "search": {
        "label": "Search",
        "href": "/search",
        "icon": "search",
        "path": "Search.ps1"
    },
    "userManagement": {
        "label": "Manage Users",
        "icon": "users-rectangle",
        "children": [
            {
                "label": "All Users",
                "icon": "user",
                "href": "/users/list",
                "path": "/users/ListUser.ps1"
            },
            {
                "label": "Onboard",
                "icon": "user-plus",
                "href": "/users/onboard",
                "path": "/users/OnboardUser.ps1",
                "roles": [
                    "PowerIAM Administrators",
                    "PowerIAM Operators"
                ]
            },
            {
                "label": "Offboard",
                "icon": "user-minus",
                "href": "/users/offboard",
                "path": "/users/OffboardUser.ps1",
                "roles": [
                    "PowerIAM Administrators",
                    "PowerIAM Operators"
                ]
            }
        ]
    },
    "groupManagement": {
        "label": "Manage Groups",
        "icon": "user-group",
        "children": [
            {
                "label": "All Groups",
                "icon": "user-group",
                "href": "/groups/list",
                "path": "/groups/ListGroups.ps1"
            }
        ]
    },
    "operations": {
        "label": "Monitoring",
        "icon": "chart-line",
        "roles": [
            "PowerIAM Administrators",
            "PowerIAM Operators"
        ],
        "children": [
            {
                "label": "Cache",
                "href": "/monitoring/cache",
                "icon": "download",
                "path": "/monitoring/cache.ps1"
            }
        ]
    },
    "settings": {
        "label": "Settings",
        "href": "/settings",
        "path": "/settings/settings.ps1",
        "icon": "gear",
        "roles": [
            "Administrator",
            "PowerIAM Administrators"
        ],
        "children": [
            {
                "label": "Mapping Rules",
                "icon": "map",
                "href": "/settings/objectmap",
                "path": "/settings/MapRules.ps1",
                "roles": [
                    "PowerIAM Administrators",
                    "PowerIAM Operators"
                ]
            },
            {
                "label": "AD Data",
                "icon": "database",
                "href": "/settings/data",
                "path": "/settings/Data.ps1",
                "roles": [
                    "PowerIAM Administrators",
                    "PowerIAM Operators"
                ]
            },
            {
                "label": "Email",
                "icon": "paper-plane",
                "href": "/settings/email",
                "path": "/settings/EmailSettings.ps1",
                "roles": [
                    "PowerIAM Administrators",
                    "PowerIAM Operators"
                ]
            }
        ]
    }
}
